### Variables
@url= http://localhost:3000/api/v1/foodtruck
@id = 3

### Get all menu items 
GET {{url}}/menu

### Get all events 
GET {{url}}/events

### GET menu by id
GET {{url}}/menu/{{id}}

### GET event by id
GET {{url}}/events/{{id}}

### POST/ add new menu item 
### I added this item in already so you will want to change the information for the db if you want to test it
### The issue was with "imageUrl", I capitalized URL.....now it is working... (bw)
POST {{url}}/menu/add
Content-Type: application/json

{
    "name": "Spicy Shrimp Taco",
    "description": "Grilled shrimp marinated in chipotle lime sauce, topped with crunchy slaw and a drizzle of creamy cilantro aioli.",
    "price": 7.50,
    "imageUrl": "https://therecipecritic.com/wp-content/uploads/2022/12/shrimp_tacos-1.jpg",
    "id": 7
}

### POST/ add new event item 
### I added this item in already so you will want to change the information for the db if you want to test it
POST {{url}}/events/add
Content-Type: application/json

{
    "name": "Pulling For Honor",
    "location": "Appleton International Airport",
    "date": "08-17-2025",
    "time": "10:00 AM - 1:30 PM",
    "id": 7
}
